import * as dotenv from "dotenv";
import * as fs from "fs";
import * as path from "path";
import { Orchestrator } from "./orchestrator";

dotenv.config();

const logger = require("./logger");

async function main() {
  if (!process.env.OPENAI_API_KEY) {
    logger.logError("OPENAI_API_KEY is not set. Please create a .env file.");
    process.exit(1);
  }

  const topic = process.argv[2] ?? "The future of AI agents in software development";
  const orchestrator = new Orchestrator();

  try {
    const context = await orchestrator.run(topic);

    const outputDir = path.join(process.cwd(), "reports");
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

    const filename   = `report_${Date.now()}.md`;
    const outputPath = path.join(outputDir, filename);

    const fullReport = [
      `# ${context.topic}`,
      `*Generated by Multi-Agent Pipeline on ${new Date().toLocaleString()}*`,
      "", "---", "",
      "## 🔍 Research",
      context.researchOutput,
      "", "---", "",
      "## 📊 Analysis",
      context.analysisOutput,
      "", "---", "",
      "## ✍️ Final Report",
      context.finalReport,
    ].join("\n");

    fs.writeFileSync(outputPath, fullReport, "utf-8");
    logger.logInfo(`Report saved to: reports/${filename}`);
    console.log("\n" + context.finalReport.split("\n").slice(0, 20).join("\n"));

  } catch (err: any) {
    logger.logError("Pipeline failed", err);
    process.exit(1);
  }
}

main();
